### ISSUE TITLE
Fulltext test from readme fails 1 test

### ISSUE THREAD

**Issue by AndyTheFactory** [AndyTheFactory/newspaper4k#463]
<a href="https://github.com/irinaid"><img src="https://avatars.githubusercontent.com/u/1889704?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [irinaid](https://github.com/irinaid)**
_Thu Jun  4 21:57:27 2020_
_Originally opened as https://github.com/codelucas/newspaper/issues/816_

----

Output when running 
$ sudo python3 tests/unit_tests.py fulltext

[...]

FAIL: test_exhaustive (__main__.ExhaustiveFullTextCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit_tests.py", line 42, in run
    method(*args, **kw)
  File "tests/unit_tests.py", line 143, in test_exhaustive
    self.assertGreaterEqual(20, total_fulltext_failed)
AssertionError: 20 not greater than or equal to 29

----------------------------------------------------------------------
Ran 45 tests in 18.955s

FAILED (failures=1, skipped=4)

**Comment by AndyTheFactory** [comment]
old test. changed in v0.9.1
