### ISSUE TITLE
Download() does not catch the content

### ISSUE THREAD

**Issue by AndyTheFactory** [AndyTheFactory/newspaper4k#548]
<a href="https://github.com/codingbutstillalive"><img src="https://avatars.githubusercontent.com/u/10086172?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [codingbutstillalive](https://github.com/codingbutstillalive)**
_Fri Jan  7 16:59:07 2022_
_Originally opened as https://github.com/codelucas/newspaper/issues/931_

----

Hi there,

this seems to be a great library, however I does not work for the following test site:

https://www.forbes.com/sites/tonybradley/2019/01/28/cybersecurity-experts-share-insight-for-data-privacy-day-2019/

**Comment by AndyTheFactory** [comment]
Works in 0.9.3

**Comment by 2dareis2do** [comment]
I have similar issue with cloudflare e.g. 

https://londonist.com/london/things-to-do/streatham-common-kite-day-festival
or
https://www.crowdfunder.co.uk/p/streatham-common-paddling-pool

 I get the following error:

```
python3 article4d.py 
url: https://londonist.com/london/things-to-do/streatham-common-kite-day-festival
Traceback (most recent call last):
  File "/var/www/html/article4d.py", line 22, in <module>
    article.parse()
  File "/home/name/.local/lib/python3.11/site-packages/newspaper/article.py", line 451, in parse
    self.throw_if_not_downloaded_verbose()
  File "/home/name/.local/lib/python3.11/site-packages/newspaper/article.py", line 736, in throw_if_not_downloaded_verbose
    raise ArticleException(
newspaper.exceptions.ArticleException: Article `download()` failed with Website protected with Cloudflare, url: None on URL https://londonist.com/london/things-to-do/streatham-common-kite-day-festival
```

here is the code
```
from newspaper import Article
from newspaper import Config

user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0'
config = Config()

config.browser_user_agent = user_agent

url = 'https://londonist.com/london/things-to-do/streatham-common-kite-day-festival'

print(f"url: {url}")

article = Article(url, config=config)

article.download()

article.parse()
print(f"doc: {article.doc}")

# print(f"article_html: {article.article_html}")

print(f"meta_description: {article.meta_description}")
print(f"summary: {article.summary}")
print(f"title: {article.title}")
print(f"text:\n {article.text}")
print(f"top image: {article.top_image}")

for movie in article.movies:
    print(f"movie url: {movie}")

```

currently using latest (0.9.3.1)

Forbes article above works fine.

**Comment by 2dareis2do** [comment]
Couple of questions, 

1. Is there a way to capture and exception if download() errors out to makes sure output is something sensible e.g. an empty object. I guess if output is a string we know something. Perhaps setting throw_if_not_downloaded_verbose to false?
2. How do we get round the cloudflare proxy server?

**Comment by 2dareis2do** [comment]
Here https://newspaper4k.readthedocs.io/en/latest/user_guide/api_reference.html#newspaper.Article.download_state

pretty sure AticleDownloadState.SUCCESS if download() was successful,  should be ArticleDownloadState.SUCCESS if download() was successful,

**Comment by 2dareis2do** [comment]
Ok to overcome spitting out standard error I can make sure output checks for ArticleDownloadState.SUCCESS before outputting anything. Other wise return or output empty array/object or similar. Error is output as a string.

```
from newspaper import Article
from newspaper import Config
from newspaper.article import ArticleException, ArticleDownloadState

user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0'
config = Config()

config.browser_user_agent = user_agent

url = 'https://londonist.com/london/things-to-do/streatham-common-kite-day-festival/'

print(f"url: {url}")

# article = Article(url)
article = Article(url, config=config)

article.download()

ds = article.download_state

if ds == ArticleDownloadState.SUCCESS:
    
    article.parse()
    print(f"doc: {article.doc}")

    print(f"meta_description: {article.meta_description}")
    print(f"summary: {article.summary}")
    print(f"title: {article.title}")
    print(f"text:\n {article.text}")
    print(f"top image: {article.top_image}")

    for movie in article.movies:
        print(f"movie url: {movie}")
elif ds == ArticleDownloadState.FAILED_RESPONSE:
    print(f"download failed: {ds}")
```

**Comment by 2dareis2do** [comment]
Ok I have tried cloudscraper and that seems to be one way to get around cloudflare issue

e.g. 

```
from newspaper import Article
from newspaper import Config
from newspaper.article import ArticleException, ArticleDownloadState
import cloudscraper

browser={
    'browser': 'chrome',
    'platform': 'android',
    'desktop': False
}

scraper = cloudscraper.create_scraper(browser)  # returns a CloudScraper instance

user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0'
config = Config()

config.browser_user_agent = user_agent

url = 'https://londonist.com/london/things-to-do/streatham-common-kite-day-festival/'

scraped = scraper.get(url).text

article = Article('')
article.html = scraped

article.parse()

print(f"doc: {article.doc}")
print(f"article_html: {article.article_html}")
print(f"meta_description: {article.meta_description}")
print(f"summary: {article.summary}")
print(f"title: {article.title}")
print(f"text:\n {article.text}")
print(f"top image: {article.top_image}")

for movie in article.movies:
    print(f"movie url: {movie}")

```
