### ISSUE TITLE
ArticleException & MissingSchema, not working on production environment

### ISSUE THREAD

**Issue by pj8912** [AndyTheFactory/newspaper4k#638]
I am using this to fetch news before summarizing on my admin panel of my website, there are few urls which dosen't really work on production.

All most all of the news urls works well on localhost but not on production.

News URL : 
```
https://indianexpress.com/article/columns/lok-sabha-elections-decolonisation-narendra-modi-9281723/lite/
```

error : 
```
ERROR: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/readtxt/main/main.py", line 71, in get_article
    article.parse()
  File "/home/readtxt/main/venv/lib/python3.10/site-packages/newspaper/article.py", line 451, in parse
    self.throw_if_not_downloaded_verbose()
  File "/home/readtxt/main/venv/lib/python3.10/site-packages/newspaper/article.py", line 736, in throw_if_not_downloaded_verbose
    raise ArticleException(
newspaper.exceptions.ArticleException: Article `download()` failed with No connection adapters were found for ':/favicon.ico' on URL :/favicon.ico

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/readtxt/main/venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/readtxt/main/venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/readtxt/main/venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/readtxt/main/venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/readtxt/main/main.py", line 84, in get_article
    body_text = extract_text_from_website(article_url)
  File "/home/readtxt/main/get_text.py", line 7, in extract_text_from_website
    response = requests.get(url)
  File "/home/readtxt/main/venv/lib/python3.10/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/readtxt/main/venv/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/readtxt/main/venv/lib/python3.10/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/readtxt/main/venv/lib/python3.10/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/home/readtxt/main/venv/lib/python3.10/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/home/readtxt/main/venv/lib/python3.10/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'favicon.ico': No schema supplied. Perhaps you meant http://favicon.ico?

```
code : 
```
config = Configuration()
        config.browser_user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"

        article = Article(article_url, config=config)
        try:
            article.download()
            article.parse()
            
            if article.text == "":
                with sync_playwright() as p:
                    browser = p.firefox.launch()
                    page = browser.new_page()
                    page.goto(article_url)
                    article.set_html(page.content())
                    article.parse() 
            return render_template('read.html', data=article.text)
            
        except ArticleException:
            body_text = extract_text_from_website(article_url)
            return render_template('read.html', data=body_text)
        
        except MissingSchema:
            body_text = extract_text_from_website(article_url)
            return render_template('read.html', data=body_text)

        except Exception as e:
            return render_template('404.html', message="Invalid URL", e=str(e))
```

The output on my site : 
```
None
```

I saw the code for handling `ArticleException` on Jan here by @AndyTheFactory , I used that but still didn't work for this news url.
If anyone dealt with this kind of problem and fixed it, please do let me know.
Thanks.

**Comment by AndyTheFactory** [comment]
you do not seem to try to get the url you mentioned, but somehow you seem to call 
```
    body_text = extract_text_from_website(article_url)

```
with `article_url="favicon.ico"` instead of the url you mentioned

I tested the url:
https://indianexpress.com/article/columns/lok-sabha-elections-decolonisation-narendra-modi-9281723/lite/

and the article  is proper extracted

To me it seems a bug in your flask app...
