### ISSUE TITLE
[BUG] Reuters article throw download error

### ISSUE THREAD

**Issue by yudataguy** [AndyTheFactory/newspaper4k#650]
**Describe the bug**
Reuters article throws download error 

**To Reproduce**
```
Steps to reproduce the behavior, please post any code you used and the website you tried to parse/process:
Traceback (most recent call last):
  File "xyz.py", line 5, in <module>
    article = newspaper.article(
              ^^^^^^^^^^^^^^^^^^
  File ".../newspaper/__init__.py", line 63, in article
    a.parse()
  File ".../newspaper/article.py", line 451, in parse
    self.throw_if_not_downloaded_verbose()
  File ".../newspaper/article.py", line 736, in throw_if_not_downloaded_verbose
    raise ArticleException(
newspaper.exceptions.ArticleException: Article `download()` failed with Status code 401 for url None on URL https://www.reuters.com/world/us/foreign-actors-stoke-divisions-ahead-us-elections-spy-agencies-say-2024-10-22/
```

**Expected behavior**
article should return normal

**System information**
 - OS: [Macos]
 - Python version [3.12]
 - Library version [0.93]

**Comment by AndyTheFactory** [comment]
Try setting the User-Agent:

````
art = newspaper.article('https://www.reuters.com/world/us/foreign-actors-stoke-divisions-ahead-us-elections-spy-agencies-say-2024-10-22/',
                        browser_user_agent=newspaper.utils.get_useragent()
                        )

art.download()
```
